"""Create new database

Revision ID: d838c728709c
Revises: 9ea2900114e1
Create Date: 2024-11-30 09:27:51.153441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd838c728709c'
down_revision = '9ea2900114e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('endereco', sa.String(length=50), nullable=True),
    sa.Column('especialidade', sa.String(length=50), nullable=True),
    sa.Column('senha', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('senha', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=True),
    sa.Column('idHospitail', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idHospitail'], ['hospitais.id'], ),
    sa.ForeignKeyConstraint(['idUser'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consultas')
    op.drop_table('usuarios')
    op.drop_table('hospitais')
    # ### end Alembic commands ###
